### ISSUE TITLE
Cannot run program "SureMap-IndexBuilder": error=2,no such file or directory

### ISSUE THREAD

**Issue by versarchey** [Mosjava/IMOS#1]
I placed SureMap-IndexBuilder and Reference file in FASTA format in the same directory as IMOS.jar.But the problem "Exception in thread "main" java.io.IOException: Cannot run program "SureMap-IndexBuilder": error=2,no such file or directory"hapened.Why is this happening?

**Comment by Mosjava** [comment]
Thank you for your feedback. I changed the codes of IndexBuilder. I hope it works correctly now. Please download IMOS.jar again and let me know if it works for you as well.

Please do not hesitate to report any further issues.

**Comment by versarchey** [comment]
> Thank you for your feedback. I changed the codes of IndexBuilder. I hope it works correctly now. Please download IMOS.jar again and let me know if it works for you as well.
> 
> Please do not hesitate to report any further issues.

Thank you for your reply. I copyed the SureMap-IndexBuilder file to the bin folder and run the program successlly after I posted the issue yesterday. I hope the issue can help you make it works better.
